CREATE TABLE "TB_USER" (
	"USER_ID"	INT		NOT NULL,
	"USER_USERNAME"	VARCHAR(30)		NULL,
	"USER_PASSWORD"	VARCHAR(30)		NULL,
	"USER_REGIST_DATE"	DATE		NULL
);

CREATE TABLE "TB_THUMBNAIL" (
	"POST_ID"	INT		NOT NULL,
	"IMG_ID"	INT		NOT NULL
);

CREATE TABLE "TB_TAG" (
	"TAG_ID"	INT		NOT NULL,
	"TAG_NAME"	VARCHAR(30)		NULL
);

CREATE TABLE "TB_POST" (
	"POST_ID"	INT		NOT NULL,
	"POST_TITLE"	VARCHAR(90)		NULL,
	"POST_CONTENT"	VARCHAR(900)		NULL,
	"POST_REGIT_DATE"	DATE		NULL,
	"POST_UPDATE_DATE"	DATE		NULL,
	"POST_DEL_YN"	CHAR(1)		NULL,
	"POST_LIKES"	INT		NULL,
	"USER_ID"	INT		NOT NULL
);

CREATE TABLE "TB_IMG" (
	"IMG_ID"	INT		NOT NULL,
	"IMG_ORIGIN_NAME"	VARCHAR(255)		NULL,
	"IMG_SAVED_NAME"	VARCHAR(255)		NULL,
	"IMG_PATH"	VARCHAR(255)		NULL,
	"IMG_DEL_YN"	CHAR(1)		NULL,
	"IMG_SAVE_DATE"	DATE		NULL,
	"POST_ID"	INT		NOT NULL
);

CREATE TABLE "TB_POST_TAG" (
	"POST_ID"	INT		NOT NULL,
	"TAG_ID"	INT		NOT NULL
);

CREATE TABLE "TB_DOWNLOAD" (
	"DOWNLOAD_ID"	INT		NOT NULL,
	"DOWNLOAD_DATE"	DATE		NULL,
	"IMG_ID"	INT		NOT NULL
);

CREATE TABLE "TB_LIKE" (
	"POST_ID"	INT		NOT NULL,
	"USER_ID"	INT		NOT NULL
);

ALTER TABLE "TB_USER" ADD CONSTRAINT "PK_TB_USER" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "TB_THUMBNAIL" ADD CONSTRAINT "PK_TB_THUMBNAIL" PRIMARY KEY (
	"POST_ID",
	"IMG_ID"
);

ALTER TABLE "TB_TAG" ADD CONSTRAINT "PK_TB_TAG" PRIMARY KEY (
	"TAG_ID"
);

ALTER TABLE "TB_POST" ADD CONSTRAINT "PK_TB_POST" PRIMARY KEY (
	"POST_ID"
);

ALTER TABLE "TB_IMG" ADD CONSTRAINT "PK_TB_IMG" PRIMARY KEY (
	"IMG_ID"
);

ALTER TABLE "TB_POST_TAG" ADD CONSTRAINT "PK_TB_POST_TAG" PRIMARY KEY (
	"POST_ID",
	"TAG_ID"
);

ALTER TABLE "TB_DOWNLOAD" ADD CONSTRAINT "PK_TB_DOWNLOAD" PRIMARY KEY (
	"DOWNLOAD_ID"
);

ALTER TABLE "TB_LIKE" ADD CONSTRAINT "PK_TB_LIKE" PRIMARY KEY (
	"POST_ID",
	"USER_ID"
);

ALTER TABLE "TB_THUMBNAIL" ADD CONSTRAINT "FK_TB_POST_TO_TB_THUMBNAIL_1" FOREIGN KEY (
	"POST_ID"
)
REFERENCES "TB_POST" (
	"POST_ID"
);

ALTER TABLE "TB_THUMBNAIL" ADD CONSTRAINT "FK_TB_IMG_TO_TB_THUMBNAIL_1" FOREIGN KEY (
	"IMG_ID"
)
REFERENCES "TB_IMG" (
	"IMG_ID"
);

ALTER TABLE "TB_POST_TAG" ADD CONSTRAINT "FK_TB_POST_TO_TB_POST_TAG_1" FOREIGN KEY (
	"POST_ID"
)
REFERENCES "TB_POST" (
	"POST_ID"
);

ALTER TABLE "TB_POST_TAG" ADD CONSTRAINT "FK_TB_TAG_TO_TB_POST_TAG_1" FOREIGN KEY (
	"TAG_ID"
)
REFERENCES "TB_TAG" (
	"TAG_ID"
);

ALTER TABLE "TB_LIKE" ADD CONSTRAINT "FK_TB_POST_TO_TB_LIKE_1" FOREIGN KEY (
	"POST_ID"
)
REFERENCES "TB_POST" (
	"POST_ID"
);

ALTER TABLE "TB_LIKE" ADD CONSTRAINT "FK_TB_USER_TO_TB_LIKE_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "TB_USER" (
	"USER_ID"
);

CREATE SEQUENCE SEQ_TAG INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_POST INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_IMG INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_DOWNLOAD INCREMENT BY 1 START WITH 1;
